services:
  apache:
    image: tugboatqa/httpd
    commands:
      init:
        - ./debian-deps.sh
      build:
        - yarn install
        - yarn build
        - yarn pdf _book/security.pdf
        - ln -snf "${TUGBOAT_ROOT}/_book" "${DOCROOT}"
