name: "Build GitHub Pages"

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Build-GitHub-Pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Calibre
        run: |
          sudo ./install-calibre.sh

      - uses: actions/setup-node@v3
        with:
          # Be sure to keep this in sync with .tugboat/config.yml.
          node-version: 16

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          yarn install
          yarn build
          yarn pdf
          mv book.pdf _book/security.pdf
          rm _book/.gitignore

      - name: Archive build results
        uses: actions/upload-artifact@v3
        with:
          name: _book
          path: _book

  Publish-GitHub-Pages:
    runs-on: ubuntu-20.04
    needs: [Build-GitHub-Pages]
    if: github.ref == 'refs/heads/fix-pages-build'

    steps:
      - name: Download built book
        uses: actions/download-artifact@v3
        with:
          name: _book

      - name: Confirm artifacts
        run: ls -R

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          exclude_assets: '.github,build.sh,CONTRIBUTING.md,install-calibre.sh,Dockerfile,package.json,yarn.lock,renovate.json,.gitignore'
